### ISSUE TITLE
Listening on the same port used for sending

### ISSUE THREAD

**Issue by dmoranj** [mcollina/node-coap#39] opened 2015-02-13 09:16 UTC
I'm currently involved in the development of a OMA Lightweight M2M library, based on node-coap (you can find it [here](https://github.com/telefonicaid/lwm2m-node-lib) and I'm struggling with one aspect of the specification: it requires the server to communicate with the devices **using the same IP and Port** used in the registration message (a POST COAP message to the server). That IP and port is used then for bidirectional communications: the server can send COAP Messages to that address and that is the address that is expected to be used to initiate messages from the device side as well.

I'm trying to overcome this issue using a customized Agent for every request, bound to the same 5683 port where the device listens for requests originated from the server. The problem here is that this situation generates two listening handlers: the one set up in the createServer() function, and the listener for the "response" event from the request. The problem arises when a request is sent using port 5683, and the response arrives to the port with two listeners.

This wouldn't be a problem in case both handlers were called, as I could simply ignore answers in the server handler (e.g.: identified by the lack of method), but that's not the case: the answer to the request arrives exclusively to the server handler, thus leaving the response listener blocked forever.

I know this scenario may be too specific for the Lightweight M2M protocol, but I would appreciate any idea for dealing with this problem, as I'm a bit stuck with it, including any contribution I could make to the library to support this weird case.

**Comment by dmoranj** [comment] 2015-02-13 16:31
Working on this problem I've realized that the specification doesn't quite specify that *all the requests from the client* should use the same port, but that *the client should listen in the same IP and port** of the registration message. This opens makes the solution far easier: I just need read the port from the outgoing socket and, once I receive the response from the registration, open a new socket to listen in that same port.

I have a problem implementing this approach, though: I do not how to extract the port used in a request sent to the COAP Server from the req or res. I've managed to solve it temporary by modifying the OutgoingMessage class to add the address of the socket to the `_rsinfo` attribute, so it can be read later. What I wonder is: Am I missing a better option to extract that port? Will it be interesting to contribute that feature to the library, to help retrieving the address information, or does it have another way to retrieve it that I haven't seen?

**Comment by mcollina** [comment] 2015-02-13 22:01
Ahum, I think that the agent and the server might get to share the same port to support Lightweight M2M. However, I have no bandwidth to dedicate time to such a refactoring. However, if you would like to submit a PR for it, I will try my best to help. Moreover, this is an OPEN Open Source project :), and you will join us in maintaining this library.

**Comment by dmoranj** [comment] 2015-03-03 16:16
Working in the integration of the LWM2M server I have found that reusing the ports may be mandatory for the implementation, and I'm facing a crossroads with this problem. I see two options:

1. To refactor server.js and Agent.js to support same socket origin. This would imply adding COAP logic to distinguish between responses and requests to forward them to different message handlers in the socket. The problem with this approach is the amount of code that is modified (the potential impact in the current functionality is high).

2. To implement the proxy-uri option in Agents, and to add an option to the server so it can behave like a proxy. This way, the LWM2M server could behave as a proxy for its own requests, sending them with the same socket it uses to receive messages. This approach should be far less risky in relation to the current functionality, and implementing the proxy options is a useful addition to the library, but it's really ad-hoc feature for LWM2M...

So those are my doubts. Any suggestions about which to implement? I'll think about it and try to propose a solution based on any of them (still not sure about which one).

**Comment by mcollina** [comment] 2015-03-03 16:40
I would go for 1 if it was not so complex. However there is a lot that can be reused between the Agent and the Server, so some refactoring would help the codebase. 2 is also ok, even if is not something I am happy with, as it would introduce latency and unnecessary work for the server.

If I had to chose, I would have a good though on how to refactor to have 1, and if it is unfeasible than go for 2. I leave the choice to you, whatever you want to implement is good ;).

**Comment by dmoranj** [comment] 2015-03-03 17:21
I've been thinking about it, and I think both options can be implemented, 2 as a short term solution (as I need to have this working ASAP) and then 1 once I had enough time to think carefully about the refactor. 

I'll be sending a PR in the following days with 2, and I'll try to separate the proxy functionality so it can be easily disabled without a huge impact in the performance. 

Thinking about both options, I think the code in the server listener should be modified to accept some kind of middleware system (something like Connect, but not necessarily connect itself) so its easier to add or remove functionality to the server pipeline. I'll try to add this to the PR as well.

**Comment by dmoranj** [comment] 2015-03-04 08:33
I've created the PR #46  for this issue, implementing the 2 solution. I've also make some important refactors in the way the incoming request is processed (I'll use my branch to test the feasibility of this solution to the Lightweight M2M problem for the moment, as I expect there will be a long discussion about the details of the refactor).

**Comment by ClaesNilsson** [comment] 2015-05-01 13:16
Hi, 
This is an interesting discussion and I have a somewhat similar problem. Seems as we would need a true bi-directional communication feature of CoAP. 

I am experimenting with a simulated IoT device and a server, both using this CoAP library. 
The scenario starts with the IoT device sending a CoAP POST "initiate" message to the server. After ACK 2.05 the server calls a REST API in the IoT device by a COAP GET message. The host address and port of the IoT device is retrieved in the server from the request.rsinfo.address and port. Furthermore, the IoT device retrieves its own local port from response.outSocket.port so it could listen to REST API calls on this port. This works fine as long as I am running these two processes in the same computer. However, when moving the server to Amazon I get problem. This is probably caused by the firewall as any subsequent REST calls do not have the same quadruple of source and destination port host and port as the "initiate message". So I thought that using the proxy feature for all traffic might help. However, I got in to the problem that I need the address and port of the IoT device to send the REST API calls to. 
* Using rsinfo from the "initiate" message only gives the address and port of the proxy.  
* Then I tried to send the "initiate" message from the IoT device to the proxy without a proxy-uri and let a handler in the proxy server extract rsinfo. This should work according to the documentation but it seems as the proxy server does not call a handler if when proxy-uri is absent. A bug?
* Even if above works I am not sure that this is enough as the source port of each request through the proxy might use a new unique port number every time. Or could an Agent setting fix this?

Your views?

**Comment by ClaesNilsson** [comment] 2015-05-03 09:10
Hi again,
Doing some more experimentation I think that this would work. However, I have two issues that I guess are bugs:

* If a server received a request without a proxyUri field the handler of the server should be called instead of forwarding to another target server. This does now work, no handler is called in this case.
* If a GET observe request is sent through the proxy then only the first response of the request is received.

I could dig into the code but probably better that @dmoranj or @mcollina looks into this.

BR

**Comment by dmoranj** [comment] 2015-05-03 10:01
You are right, they seem to be bugs. I'll try to create test cases and fix
them on the following week.

**Comment by ClaesNilsson** [comment] 2015-05-03 20:42
Thanks a lot!

**Comment by ClaesNilsson** [comment] 2015-05-11 10:23
Hi again Daniel, sorry to be pushy but do you know when these bugs will be fixed? I am eager to try this bi-directional coap thing using your proxy solution :-)

**Comment by dmoranj** [comment] 2015-05-11 12:39
Hi Claes,

I've been quite busy with other things in this days, so I didn't have time
to spend in this bugs. I'll try to fix it this week, sorry.

**Comment by ClaesNilsson** [comment] 2015-05-11 13:27
Thanks Daniel!

**Closed** 2020-07-21 01:33 UTC
Labels: wontfix
