### ISSUE TITLE
Multicast server on Wifi Interface

### ISSUE THREAD

**Issue by damienjars** [mcollina/node-coap#147] opened 2017-05-31 13:39 UTC
Hi erveryone,
I'm hurting a big new issue about the coap server discoverable feature.

I'm trying to  connect and listen on the 224.0.1.187:5683 address, but when I'm trying to use my node.js app on Wifi, this seems to not get registered. I don't see the frame on Wireshark.

However, this works perfectly when we are using the Ethernet plugged.

Do you know why please ?

Thx

Damien

**Comment by GiedriusM** [comment] 2017-05-31 14:59
Are you sure this is node-coap issue and not your network configuration? First, capture the transmitting interface (or if you can, capture all WiFi traffic, using a sniffer) and see if the multicast packet is being sent at all.

**Comment by damienjars** [comment] 2017-06-01 12:01
Hi @GiedriusM, We are sure about our network configuration. Using Wireshark, we don't see any packet emitted from our coad server. Howerver, this multicast packet is emmitted when the PC running the coap server is plugged on ethernet wire. 

We tried on many PCs and we are facing the same issue on all. 

:(

We are wondering if this is not a Wifi issue since we know there are some troubles with mulcticasting over wifi.

**Comment by GiedriusM** [comment] 2017-06-01 12:11
@damienjars , could you try using some other tool to generate multicast UDP packet and see if they reach the destination.
For example, [iperf](https://sandilands.info/sgordon/using-multicast-on-a-lan-in-linux) could be used for this. If it can't doesn't work either, then it's almost certainly that the issue is not in node-coap, but your configuration, OS or hardware.

**Comment by damienjars** [comment] 2017-06-14 12:11
Hi @GiedriusM, we finally find out a solution. We used the library v17 and after the update, our server finally worked.

Thanks for your answers :)

**Comment by GiedriusM** [comment] 2017-06-14 12:24
@damienjars, good to know :) If this issue is fully resolved, please close it.

**Closed** 2017-06-14 12:44 UTC
